name: CI

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake --preset release
      - name: Build
        run: cmake --build build -j2
      - name: Test
        run: ctest --test-dir build --output-on-failure
